version: '3.8'

services:
  schedule-bot:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ALLOW_PUBLIC=${ALLOW_PUBLIC:-true}
    volumes:
      - ./schedule.db:/app/schedule.db 